esphome:
  name: garage

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "curSf62m6ZYe/BfelHKxG9ojGfGYfd4yBQqFc+hC3D8="

ota:
  password: "dfab7eeab40647d97bb15e37cb4aa8f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage Fallback Hotspot"
    password: "Uy2KWwwzQtY1"

captive_portal:
    

switch:
  - platform: gpio
    name: "Garage Light"
    pin:
      number: D5
      inverted: true
      mode: OUTPUT_OPEN_DRAIN
    id: garage_light


script:
  - id: run_garage_light
    then:
      - switch.turn_on: garage_light
      - delay: 120s
      - switch.turn_off: garage_light

binary_sensor:
  - platform: gpio
    device_class: garage_door
    name: "Front Garage"
    pin:
       number: D1
       mode: INPUT_PULLUP   
       inverted: false
    on_state:
      then:
        - script.stop: run_garage_light
        - script.execute: run_garage_light
  - platform: gpio
    name: "Rear Garage"
    device_class: garage_door
    pin: 
      number: D2
      mode: INPUT_PULLUP
      inverted: false
    on_state:
      then:
        - script.stop: run_garage_light
        - script.execute: run_garage_light
  - platform: gpio
    name: "Garage Motion"
    device_class: "motion"
    pin: 
      number: D6
      mode: INPUT_PULLUP
      inverted: false
    on_press: 
      then:
        - script.stop: run_garage_light
        - script.execute: run_garage_light
    
    

